### ISSUE TITLE
Contributing Workflow

### ISSUE THREAD

**Issue by cookiengineer** [mk-fg/apparmor-profiles#1]
Hey,

I just found this project and I think it is an amazing idea! I had the same whilst wondering why there is no really centralized apparmor profiles repository.

Would it make sense to merge in the apparmor-profiles from Ubuntu here?
Many of them are just stub files and I think fixing them would be pretty important:

http://bazaar.launchpad.net/~apparmor-dev/apparmor-profiles/master/files/head:/ubuntu/14.04/

**Comment by kortewegdevries** [comment]
@mk-fg  Do you accept profile PRs for this repo?

**Comment by mk-fg** [comment]
Probably not.
If there's a bug, would be happy to merge a patch, but don't see much point in adding profiles or permissions for e.g. stuff that I don't use myself, as it's a kind of "customized dotfiles" repo, not something that's intended to cover everyone's apps and use-cases.
