### ISSUE TITLE
Steam home access

### ISSUE THREAD

**Issue by hadogenes** [mk-fg/apparmor-profiles#4]
https://github.com/mk-fg/apparmor-profiles/blob/4f0c5af4cd8763db1fe0097ca1d230125bc8a961/profiles/usr.bin.steam#L20
I think Steam should not have full access to home dir - only the his config dir

**Comment by mk-fg** [comment]
I've used it with dedicated uid/home (as mentioned in the comment just above that), so wasn't an issue - there was nothing in there but steam's own stuff.
Otherwise yeah, probably should not have this kind of access.
